### ISSUE TITLE
Block types with broken edit views

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-app-library-authoring#68]
Some of the block types are not editable in the MFE (it's especially notable because of the 3 not in the "Advanced" dropdown, only 1 works)

| Block Type | Working? | Error Message |
| - | - | - |
| Completion | ✅ | |
| Drag and Drop | ✅ | |
| Google Calendar | ✅ | |
| Google Document | ✅ | |
| Poll | ✅ | |
| Provide Feedback | ✅ | |
| Survey | ✅ | |
| Video | ❌ | [TemplateDoesNotExist.zip](https://github.com/openedx/frontend-app-library-authoring/files/9648961/TemplateDoesNotExist.zip) |
| Word cloud | ❌ | [NoSuchServiceError.zip](https://github.com/openedx/frontend-app-library-authoring/files/9649010/NoSuchServiceError.zip) |
| HTML | ❌ | Does not use new React-based editor|
| Advanced Problem | ❌ | [TemplateDoesNotExist.zip](https://github.com/openedx/frontend-app-library-authoring/files/9649046/TemplateDoesNotExist.zip) |

### Proposed solution

The fix for the Video, HTML, and Problem blocks is to use the new React-based editors.  These editors are currently only usable via the Course Authoring MFE.  If the corresponding waffle flags are enabled (for instance [new_core_editors.use_new_text_editor](https://github.com/openedx/edx-platform/blob/master/cms/djangoapps/contentstore/toggles.py#L96)), when the user edits the corresponding block in Studio, they [are sent to the Course Authoring MFE](https://github.com/openedx/edx-platform/blob/master/cms/static/js/views/pages/container.js#L198).

The Course Authoring MFE, in turn, [imports](https://github.com/openedx/frontend-app-course-authoring/blob/master/src/editors/EditorContainer.jsx#L4) the editors themselves [from frontend-lib-content-components](https://github.com/openedx/frontend-lib-content-components/blob/main/src/editors/EditorPage.jsx).  As an MFE in its own right, the Library Authoring MFE should do the same.

**Comment by arbrandes** [comment]
Video, Problem and HTML will likely come out of the new editors being developed for frontend-app-course-authoring.  (The editors themselves are hosted in https://github.com/edx/frontend-lib-content-components/).

**Comment by jristau1984** [comment]
@arbrandes is correct.  Our rollout of the new Text/HTML editor for Course Authoring was automatically applied to the Library Authoring context as well.  This is also true for the new Video Settings Editor which is currently in Beta testing.  

I do not believe there will need to be anything special or unique done for these new editors to apply to the Library Authoring context.  

Based on that, @brian-smith-tcril do you still want to keep this issue open?

**Comment by arbrandes** [comment]
@jristau1984, @brian-smith-tcril, see the Proposed Solution in the ticket description.  We're going to need to import and use the new editors in this MFE, just like Course Authoring does.

**Comment by jristau1984** [comment]
We are aware of this, and this integration work is part of the library authoring MFE rollout work that is currently being planned.  We expect this to be completed in Q1 2023.  Don't hesitate to reach out with any questions/comments/concerns.  Thanks!

**Comment by arbrandes** [comment]
@jristau1984, Any objections to us (as in @brian-smith-tcril) tackling this sooner rather than later?  Is the work already in progress?

**Comment by jristau1984** [comment]
What exactly are you proposing to do?

Thanks,
Jeremy Ristau
Engineering Manager - edX/2U

**Comment by brian-smith-tcril** [comment]
> ### Proposed solution
> The fix for the Video, HTML, and Problem blocks is to use the new React-based editors.

**Comment by arbrandes** [comment]
Yeah, see "Proposed Solution" above.  Basically, to do here exactly what the Course Authoring MFE does: import the editors from `frontend-lib-content-components`.  (As opposed to redirecting to the Course Authoring MFE.)

**Comment by jristau1984** [comment]
Ahh, sorry I understand now you are proposing just the import portion of the work.  That I have no issues with, but please coordinate with @connorhaugh as he is working on getting the library authoring MFE ready for beta test and I would prefer to not have duplicative updates.

More info:
1. Yes, Editor overhauls are well on their way.  Text and Video Settings Editors are rolled out in edx.org, and the Visual Problem Editor should begin a beta test within the next two weeks.
2. For the Library Authoring MFE, since it is not rolled out in edx.org I personally have no issues with making this update.  Additionally, since the current MFE does not have functioning editors this feels "just as safe" for any and all Open edX instances.

**Comment by connorhaugh** [comment]
@arbrandes
A little more information. I will send you the set more complex set of tasks which solves the criteria "a user can CRUD problems, videos, and text components in the library authoring MFE using the new editors." 
Those tasks roughly, are:
- Fix "new problem xblock" button in Lib-authoring to match expected behavior
- Replace existing edit page with new editors.
- Reconcile static asset apis in new editors to match learning context.

**Comment by arbrandes** [comment]
If I'm not mistaken, this has now been solved, right?
